name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      test:
        description: random junk
        # required: true
        default: junky junk
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t takeactionplayground:test .

    - name: Run Docker image
      run: docker run -d -p 80:80 --rm takeactionplayground:test

    - name: Curl endpoint
      id: curl_check
      run: echo "result=$(curl -s http://localhost/ | jq -c .)" | tee -a $GITHUB_OUTPUT

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Version
      run: terraform version

    - name: Check curl output
      if: ${{ fromJson(steps.curl_check.outputs.result).shades == 'Shades' }}
      run: echo "Yes, shades."

    # - name: Echo list
    #   # This bullshit nonsense will echo "Array" and not the contets of the array.
    #   run: echo ${{ fromJson(steps.curl_check.outputs.result).listyStuff }}

    - name: Set matrix
      id: set-matrix
      run: |
        echo "matrix=$(echo '${{ steps.curl_check.outputs.result }}' | jq -c '{listyStuff: .listyStuff}')" | tee -a $GITHUB_OUTPUT

    - name: Tag valid docker image
      id: tag_docker
      run: docker tag takeactionplayground:test takeactionplayground:release

    - name: Clean up Docker environment
      run: docker kill $(docker ps -q)

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  use_matrix:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
    steps:
      - name: Use array element
        run: echo "Current element is ${{ matrix.listyStuff }}"
