name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t takeactionplayground:test .

    - name: Run Docker image
      run: docker run -d -p 80:80 --rm takeactionplayground:test

    - name: Curl endpoint
      run: curl -s http://localhost/

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Version
      run: terraform version

    - name: Clean up Docker environment
      run: docker kill $(docker ps -q)

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     push: false
    #     tags: devdull/takeactionplayground:latest
    # - name: Run Docker image
    #   run: |
    #     docker pull devdull/takeactionplayground:latest
    #     docker run --rm devdull/takeactionplayground:latest