name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t takeactionplayground:test .

    - name: Run Docker image
      run: docker run -d -p 80:80 --rm takeactionplayground:test

    - name: Curl endpoint
      id: curl_check
      run: echo "result=$(curl -s http://localhost/ | tr '\n' ' ' | grep -o shades)" | tee -a $GITHUB_OUTPUT

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Version
      run: terraform version

    - name: Check curl output
      if: ${{ steps.curl_check.outputs.result != 'shades' }}
      run: echo "Yes, shades." >&2; exit 1

    - name: Tag valid docker image
      id: tag_docker
      run: docker tag takeactionplayground:test takeactionplayground:release

    - name: Clean up Docker environment
      run: docker kill $(docker ps -q)

  cheese_lover:
    name: 'Cheese Lover'
    runs-on: ubuntu-latest
    steps:
    - name: Express Love for Cheese
      run: echo "yes, I like cheese"