name: Create New Version and Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version increment type (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
  create_version_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.event.inputs.version_type }}
          WITH_V: true

      # - name: Create additional tags
      #   if: ${{ steps.bump_version.outputs.new_tag != '' }}
      #   run: |
      #     # Extract major, minor, and patch versions
      #     NEW_TAG=${{ steps.bump_version.outputs.new_tag }}
      #     MAJOR=$(echo $NEW_TAG | cut -d. -f1)
      #     MINOR=$(echo $NEW_TAG | cut -d. -f2)

      #     # Create and push vMAJOR and vMAJOR.MINOR tags
      #     git tag "v${MAJOR}"
      #     git tag "v${MAJOR}.${MINOR}"
      #     git push origin "v${MAJOR}" "v${MAJOR}.${MINOR}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cut Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          generate_release_notes: true
          files: '*'  # TODO: Narrow scope to specific action directories

